"""initial schema

Revision ID: 90dcec7b5c6e
Revises: 
Create Date: 2026-10-04 00:03:39.235011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90dcec7b5c6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missed_dose_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('late_dose_after_minutes', sa.Integer(), nullable=False),
    sa.Column('device_warning_after_minutes', sa.Integer(), nullable=False),
    sa.Column('device_offline_after_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'caretaker')", name='role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medicine_due', sa.Boolean(), nullable=False),
    sa.Column('medicine_dispensed', sa.Boolean(), nullable=False),
    sa.Column('medicine_taken', sa.Boolean(), nullable=False),
    sa.Column('medicine_missed', sa.Boolean(), nullable=False),
    sa.Column('device_offline', sa.Boolean(), nullable=False),
    sa.Column('device_online', sa.Boolean(), nullable=False),
    sa.Column('device_error', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_caretaker_id'), 'patients', ['caretaker_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=128), nullable=False),
    sa.Column('auth', sa.String(length=64), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('signal_strength', sa.SmallInteger(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_state', sa.String(length=16), nullable=True),
    sa.Column('last_error', sa.String(length=200), nullable=True),
    sa.Column('offline_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_uid')
    )
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_devices_patient_id'), 'devices', ['patient_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('generic_name', sa.String(length=120), nullable=True),
    sa.Column('dose_quantity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('dose_unit', sa.String(length=24), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_patient_id'), 'medicines', ['patient_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_device_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('medicine_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('dose_quantity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period IN ('morning', 'afternoon', 'evening', 'night')", name='period_valid'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='dates_ordered'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_schedules_medicine_id'), 'medicine_schedules', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_medicine_schedules_patient_id'), 'medicine_schedules', ['patient_id'], unique=False)
    op.create_table('medicine_doses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('medicine_name', sa.String(length=120), nullable=False),
    sa.Column('dose_quantity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('dose_unit', sa.String(length=24), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'due', 'dispensed', 'taken', 'missed', 'cancelled')", name='status_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['medicine_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_for', name='uq_dose_schedule_time')
    )
    op.create_index('ix_dose_patient_time', 'medicine_doses', ['patient_id', 'scheduled_for'], unique=False)
    op.create_index('ix_dose_status_time', 'medicine_doses', ['status', 'scheduled_for'], unique=False)
    op.create_table('medicine_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('dose_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("event_type IN ('medicine_due', 'medicine_dispensed', 'medicine_taken', 'medicine_missed', 'medicine_cancelled', 'device_online', 'device_offline', 'device_error')", name='event_type_valid'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dose_id'], ['medicine_doses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_event_patient_time', 'medicine_events', ['patient_id', 'event_time'], unique=False)
    op.create_index('ix_event_received', 'medicine_events', ['received_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('dose_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_sent', sa.Integer(), nullable=False),
    sa.Column('push_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('medicine_due', 'medicine_dispensed', 'medicine_taken', 'medicine_missed', 'device_offline', 'device_online', 'device_error', 'test')", name='type_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dose_id'], ['medicine_doses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index('ix_notification_user_time', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_user_time', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_event_received', table_name='medicine_events')
    op.drop_index('ix_event_patient_time', table_name='medicine_events')
    op.drop_table('medicine_events')
    op.drop_index('ix_dose_status_time', table_name='medicine_doses')
    op.drop_index('ix_dose_patient_time', table_name='medicine_doses')
    op.drop_table('medicine_doses')
    op.drop_index(op.f('ix_medicine_schedules_patient_id'), table_name='medicine_schedules')
    op.drop_index(op.f('ix_medicine_schedules_medicine_id'), table_name='medicine_schedules')
    op.drop_table('medicine_schedules')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_medicines_patient_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_devices_patient_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_patients_caretaker_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('notification_preferences')
    op.drop_table('users')
    op.drop_table('system_config')
    # ### end Alembic commands ###
